### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by beyzakkoyunlu** [rsagroup/rsatoolbox#197]
I use Python 3.6.8 and I installed rsatoolbox using pip. However when I try to import it, I get the following error 

`Traceback (most recent call last):

  File "/neuro_tools/virt_envs/beyza/fmri/lib64/python3.6/site-packages/IPython/core/interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-1-e81955bc16b3>", line 1, in <module>
    import rsatoolbox

  File "/neuro_tools/virt_envs/beyza/rsa_fmri/lib/python3.6/site-packages/rsatoolbox/__init__.py", line 7, in <module>
    from . import inference

  File "/neuro_tools/virt_envs/beyza/rsa_fmri/lib/python3.6/site-packages/rsatoolbox/inference/__init__.py", line 4, in <module>
    from .evaluate import eval_fancy

  File "/neuro_tools/virt_envs/beyza/rsa_fmri/lib/python3.6/site-packages/rsatoolbox/inference/evaluate.py", line 9, in <module>
    from rsatoolbox.rdm import compare

  File "/neuro_tools/virt_envs/beyza/rsa_fmri/lib/python3.6/site-packages/rsatoolbox/rdm/__init__.py", line 1, in <module>
    from .rdms import RDMs

  File "/neuro_tools/virt_envs/beyza/rsa_fmri/lib/python3.6/site-packages/rsatoolbox/rdm/rdms.py", line 11, in <module>
    from rsatoolbox.rdm.combine import _mean

  File "/neuro_tools/virt_envs/beyza/rsa_fmri/lib/python3.6/site-packages/rsatoolbox/rdm/combine.py", line 3
    from __future__ import annotations
                                      ^
SyntaxError: future feature annotations is not defined
`

**Comment by JasperVanDenBosch** [comment]
hi @beyzakkoyunlu,
sorry, we don't support python 3.6 anymore. This should work on python 3.7

**Comment by beyzakkoyunlu** [comment]
Thanks, I didn't catch that

**Comment by JasperVanDenBosch** [comment]
No worries, it's a recent change and we could do a better job of displaying it.
Don't hesitate to be in touch if you get stuck with anything else
